package uz.pdp.botcamp.constants;

public enum UserLastOperation {
    ADD_DESCRIPTION,
    ADD_PRODUCT,
    ASK_CODE,
    ASK_PHONENUMBER_FOR,
    ASK_PRODUCT_NAME,
    ASK_PRODUCT_PHOTO,
    ASK_PRODUCT_PRICE,

    ASK_PRODUCT_URL,
    CHOOSE_DEFAULT_PHOTO,
    CREATE_CATEGORY,
    DELETE_PRODUCT,


    EDITE_PRODUCT,
    EDIT_NAME,
    EDIT_PRICE,
    OPERATION_WITH_CART,
    OPERATION_WITH_CATEGORY,
    OPERATION_WITH_PRODUCT,


    OPERATION_WITH_SETTING,
    OPERATION_WITH_USER,
    SELECT_AMOUNT,
    SELECT_MENU,

    SEND_COUNTRY,
    SEND_DISTRICT,
    SEND_HOMENUMBER,
    SEND_LOCATION,
    SEND_PDF_OFFER,
    SEND_REGION,
    SEND_STREET,

    SHOW_CATEGORY,
    SHOW_NEW_OFER,
    SHOW_OFFER,

    SHOW_OLD_OFER,
    SHOW_PRODUCT,
    START,
    WRITE_DESCRIPTION, CHAGE_USER_OPERATION, ADD_CATEGORY, DELETE_CATEGORY, EDIT_CATEGORY_NAME, EDIT_PHOTO, NEW_PHOTO, NEW_URL, SHOW_CART,

}
